# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.29.0
    hooks:
      - id: eslint
        files: \.tsx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        args: [--parser-options=project:frontend/tsconfig.json]
