name: JUnit

on:
  pull_request:
    branches:
      - main
      - production
    paths:
      - backend/**.java

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build
        working-directory: backend
        run: mvn --batch-mode -DskipTests package

      - name: Test
        working-directory: backend
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          working-directory: backend
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
