name: ESLint

on:
  pull_request:
    branches:
      - main
      - production
    paths:
      - frontend/**.ts
      - frontend/**.tsx

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        working-directory: frontend
        run: yarn
      - name: Run ESLint
        working-directory: frontend
        run: yarn lint
