name: Integration test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - production

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Build backend"
        working-directory: backend
        run: docker build -t springio/gs-spring-boot-docker . --build-arg SECRET_PASSPHRASE=se2022_group4
      - name: "Frontend dependency"
        working-directory: frontend
        run: yarn
      - name: "Start test"
        working-directory: frontend
        run: |-
          docker run -p 8080:8080 springio/gs-spring-boot-docker &
          sleep 21s
          echo $(docker ps)
          echo $(curl -v "http://localhost:8080/nearbyAttractions?longitude=121.5654268&latitude=25.0329636")
          yarn ijest
        env:
          API_ROOT: http://localhost:8080
